services:
  server:
    image: user1313/dev_env:slim
    volumes:
      - .:/app
    ports:
      - "1313:1313"
    command: /bin/sh -c "while true; do sleep 1; done"
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
