services:
  server:
    image: user1313/dev_env:latest
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "1313:1313"
      - "3000:3000"
    command: /bin/sh -c "while sleep 500; do :; done"
  db-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
